service: serverless-base

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10

functions:

  getBar:
    handler: functions/bar.default
    events:
      - http: GET bar

  getFoo:
    handler: functions/foo.default
    events:
          - http: GET foo

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true